# -*- coding: utf-8 -*-
"""StochCalc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMLTFz4FexWU-if6xZUUn-0qgsIVAqrY
"""

# ── Install dependencies ───────────────────────────────────────────────────
import subprocess, sys
pkgs = ["yfinance", "statsmodels", "pandas", "numpy",
        "matplotlib", "seaborn", "torch", "scikit-learn", "tqdm"]
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *pkgs])
print("All packages ready.")

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from itertools import combinations
from tqdm.auto import tqdm

import yfinance as yf
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.vector_ar.vecm import coint_johansen
from statsmodels.regression.linear_model import OLS
from statsmodels.tools import add_constant

import torch
import torch.nn as nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from torch.utils.data import DataLoader, TensorDataset

SEED = 42
np.random.seed(SEED)
torch.manual_seed(SEED)
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

plt.rcParams.update({
    "figure.dpi": 130,
    "axes.spines.top": False,
    "axes.spines.right": False,
    "axes.grid": True,
    "grid.alpha": 0.3,
    "font.size": 11,
})
COLORS = ["#2563EB", "#DC2626", "#16A34A", "#D97706", "#7C3AED"]
print(f"Device: {DEVICE}")

# ── Configuration ──────────────────────────────────────────────────────────
TICKERS = [
    "HDFCBANK.NS", "ICICIBANK.NS", "AXISBANK.NS",
    "KOTAKBANK.NS", "SBIN.NS", "BANKBARODA.NS",
    "INDUSINDBK.NS", "FEDERALBNK.NS",
]
DATE_RANGE        = ("2019-01-01", "2024-12-31")
TRAIN_FRAC        = 0.80
TRANSACTION_COST  = 0.0005   # 5 bps per trade

raw = yf.download(TICKERS, start=DATE_RANGE[0], end=DATE_RANGE[1],
                  auto_adjust=True, progress=False)["Close"]
prices = raw.dropna(axis=1, thresh=int(0.9 * len(raw))).ffill().dropna()

print(f"Loaded {prices.shape[1]} tickers x {len(prices)} trading days")
print(f"Date range: {prices.index[0].date()} -> {prices.index[-1].date()}")
prices.head(3)

split_idx    = int(len(prices) * TRAIN_FRAC)
train_prices = prices.iloc[:split_idx].copy()
test_prices  = prices.iloc[split_idx:].copy()

print(f"Train: {train_prices.index[0].date()} -> {train_prices.index[-1].date()} ({len(train_prices)} days)")
print(f"Test : {test_prices.index[0].date()} -> {test_prices.index[-1].date()} ({len(test_prices)} days)")

# ════════════════════════════════════════════════════════════════════════════
#  Helper functions — each maps to an equation in the reference document
# ════════════════════════════════════════════════════════════════════════════

def normalise_prices(df):
    return df / df.iloc[0]


def ssd_matrix(df):
    """Sum-of-squared deviations between every normalised pair (pipeline step 1)."""
    norm = normalise_prices(df)
    cols = df.columns.tolist()
    records = []
    for a, b in combinations(cols, 2):
        ssd = ((norm[a] - norm[b]) ** 2).sum()
        records.append({"s1": a, "s2": b, "ssd": ssd})
    return pd.DataFrame(records).sort_values("ssd").reset_index(drop=True)


def adf_pval(series):
    """ADF p-value — want p > 0.05 to confirm I(1) (Eq. 12-13)."""
    return adfuller(series, autolag="AIC")[1]


def johansen_hedge_ratio(s1, s2):
    """
    Johansen test. Returns beta* from leading eigenvector,
    trace stat, and 5% critical value (Eq. 22-24).
    """
    df2 = pd.concat([s1, s2], axis=1).dropna()
    res = coint_johansen(df2, det_order=0, k_ar_diff=1)
    trace_stat = res.lr1[0]
    crit_val_5 = res.cvt[0, 1]
    ev         = res.evec[:, 0]
    beta_star  = -ev[0] / ev[1]   # Eq. 24
    return {
        "beta": beta_star,
        "trace_stat": trace_stat,
        "crit_val_5": crit_val_5,
        "cointegrated": trace_stat > crit_val_5,
    }


def fit_ou_params(spread):
    """
    Estimate OU parameters via OLS on DeltaZ = a + b*Z_{t-1} + eps (Eq. 25-28).
    Returns theta, mu, sigma, half_life.
    """
    dz    = spread.diff().dropna()
    z_lag = spread.shift(1).dropna()
    z_lag, dz = z_lag.align(dz, join="inner")
    reg   = OLS(dz, add_constant(z_lag)).fit()
    a, b  = reg.params
    theta     = max(-b, 1e-6)
    mu        = a / theta
    sigma     = reg.resid.std()
    half_life = np.log(2) / theta   # Eq. 10
    return {"theta": theta, "mu": mu, "sigma": sigma, "half_life": half_life}


def hurst_exponent(series, max_lag=100):
    """
    Hurst exponent via log-log regression of lagged std deviations (Eq. 31).
    H < 0.5 -> mean-reverting.
    """
    lags = range(2, min(max_lag, len(series) // 4))
    tau  = [np.std(np.subtract(series[lag:].values, series[:-lag].values))
            for lag in lags]
    tau      = np.array(tau)
    lags_arr = np.array(list(lags))
    valid    = tau > 0
    if valid.sum() < 3:
        return 0.5
    poly = np.polyfit(np.log(lags_arr[valid]), np.log(tau[valid]), 1)
    return float(poly[0])


print("Helper functions defined.")

HALF_LIFE_MIN = 2
HALF_LIFE_MAX = 180  # Increased from 30 to allow more pairs to be found
HURST_MAX     = 0.45
ADF_PVAL_MIN  = 0.05
TOP_N_SSD     = 20

results = []
ssd_df  = ssd_matrix(train_prices)

print(f"Running Johansen + OU + Hurst on top-{TOP_N_SSD} SSD pairs...")
for _, row in tqdm(ssd_df.head(TOP_N_SSD).iterrows(), total=TOP_N_SSD):
    s1_name, s2_name = row["s1"], row["s2"]
    s1 = train_prices[s1_name]
    s2 = train_prices[s2_name]

    # Step 1: confirm I(1)
    p1, p2 = adf_pval(s1), adf_pval(s2)
    if p1 < ADF_PVAL_MIN or p2 < ADF_PVAL_MIN:
        continue

    # Step 2: Johansen
    joh = johansen_hedge_ratio(s1, s2)
    if not joh["cointegrated"]:
        continue

    # Step 3: OU
    spread = s1 - joh["beta"] * s2
    ou = fit_ou_params(spread)
    if not (HALF_LIFE_MIN < ou["half_life"] < HALF_LIFE_MAX):
        continue

    # Step 4: Hurst
    H = hurst_exponent(spread)
    if H >= HURST_MAX:
        continue

    results.append({
        "s1": s1_name, "s2": s2_name,
        "ssd": row["ssd"],
        "beta": joh["beta"],
        "trace_stat": joh["trace_stat"],
        "crit_val_5": joh["crit_val_5"],
        "adf_p1": p1, "adf_p2": p2,
        "theta": ou["theta"], "mu": ou["mu"],
        "sigma": ou["sigma"], "half_life": ou["half_life"],
        "hurst": H,
    })

pairs_df = pd.DataFrame(results).sort_values("half_life").reset_index(drop=True)
print(f"\n{len(pairs_df)} pair(s) passed all filters:")
print(pairs_df[["s1","s2","beta","half_life","hurst","theta","sigma","trace_stat"]]
      .to_string(index=False, float_format="{:.4f}".format))

assert len(pairs_df) > 0, "No cointegrated pairs found — try broadening the universe or date range."

best        = pairs_df.iloc[0]
S1_NAME     = best["s1"]
S2_NAME     = best["s2"]
BETA_STATIC = best["beta"]
OU_MU       = best["mu"]
OU_THETA    = best["theta"]
OU_SIGMA    = best["sigma"]
HALF_LIFE   = best["half_life"]

print(f"Best pair : {S1_NAME} / {S2_NAME}")
print(f"  beta*   = {BETA_STATIC:.4f}")
print(f"  theta   = {OU_THETA:.4f}  (mean reversion speed)")
print(f"  mu      = {OU_MU:.4f}  (long-run spread mean)")
print(f"  sigma   = {OU_SIGMA:.4f}")
print(f"  half-life = {HALF_LIFE:.1f} days")
print(f"  Hurst H = {best['hurst']:.4f}")

train_spread = train_prices[S1_NAME] - BETA_STATIC * train_prices[S2_NAME]

fig, axes = plt.subplots(2, 1, figsize=(14, 7),
                         gridspec_kw={"height_ratios": [2, 1]})

norm = normalise_prices(train_prices[[S1_NAME, S2_NAME]])
norm[S1_NAME].plot(ax=axes[0], color=COLORS[0], label=S1_NAME)
norm[S2_NAME].plot(ax=axes[0], color=COLORS[1], label=S2_NAME)
axes[0].set_title(f"Normalised Prices — {S1_NAME} vs {S2_NAME} (Train)", fontweight="bold")
axes[0].legend()
axes[0].set_ylabel("Normalised Price")

train_spread.plot(ax=axes[1], color=COLORS[2], lw=0.9, label="Spread Z")
axes[1].axhline(OU_MU, color="black", ls="--", lw=1.0, label=f"mu={OU_MU:.2f}")
axes[1].set_title(f"Cointegrated Spread  Z = {S1_NAME} - {BETA_STATIC:.3f} x {S2_NAME}")
axes[1].legend()
axes[1].set_ylabel("Spread (INR)")

plt.tight_layout()
plt.show()

class PairsLSTM(nn.Module):
    """
    Two-layer stacked LSTM. Maps a window of locally-normalised log-prices
    to OU parameters (beta_t, theta_t, mu_t).

    Input  : (batch, seq_len, 2)   locally normalised log-prices of s1, s2
    Output : beta (B,), theta (B,) >0, mu (B,)
    """
    def __init__(self, input_dim=2, hidden_dim=64, num_layers=2, dropout=0.2):
        super().__init__()
        self.lstm = nn.LSTM(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout if num_layers > 1 else 0.0,
        )
        self.head_beta  = nn.Linear(hidden_dim, 1)
        self.head_theta = nn.Linear(hidden_dim, 1)   # exp() enforces >0 (Eq. 39)
        self.head_mu    = nn.Linear(hidden_dim, 1)

    def forward(self, x):
        out, _ = self.lstm(x)
        h = out[:, -1, :]
        beta  = self.head_beta(h).squeeze(-1)
        theta = torch.exp(self.head_theta(h)).squeeze(-1)
        mu    = self.head_mu(h).squeeze(-1)
        return beta, theta, mu


# Sanity check
_m = PairsLSTM().to(DEVICE)
_x = torch.randn(4, 60, 2).to(DEVICE)
_b, _t, _u = _m(_x)
assert _b.shape == (4,) and (_t > 0).all()
n_params = sum(p.numel() for p in _m.parameters())
print(f"PairsLSTM — {n_params:,} parameters  |  theta always >0: {(_t>0).all()}")
del _m, _x, _b, _t, _u

WINDOW        = max(int(HALF_LIFE * 2) + 5, 30)   # adaptive window ~ 2 x half-life
BATCH_SIZE    = 64
EPOCHS        = 80
LR            = 3e-4
LAMBDA_SMOOTH = 0.05

print(f"Window size: {WINDOW} days  (approx 2 x half-life={HALF_LIFE:.1f})")


def make_windows(df, s1, s2, window):
    """
    Build (N, window, 2) tensor of locally-normalised log-prices (Remark 3.1).
    Normalise each window: subtract mean, divide by std.
    """
    log1 = np.log(df[s1].values.astype(np.float32))
    log2 = np.log(df[s2].values.astype(np.float32))
    N = len(df) - window + 1
    X = np.empty((N, window, 2), dtype=np.float32)
    for i in range(N):
        w1 = log1[i:i + window]
        w2 = log2[i:i + window]
        X[i, :, 0] = (w1 - w1.mean()) / (w1.std() + 1e-8)
        X[i, :, 1] = (w2 - w2.mean()) / (w2.std() + 1e-8)
    return torch.from_numpy(X)


X_train  = make_windows(train_prices, S1_NAME, S2_NAME, WINDOW)
n_val    = max(int(0.2 * len(X_train)), 1)
X_val    = X_train[-n_val:]
X_tr     = X_train[:-n_val]

train_dl = DataLoader(TensorDataset(X_tr),  batch_size=BATCH_SIZE, shuffle=True,  drop_last=True)
val_dl   = DataLoader(TensorDataset(X_val), batch_size=BATCH_SIZE, shuffle=False, drop_last=True)

print(f"Train windows: {len(X_tr):,}   Val windows: {len(X_val):,}")

def stationarity_loss(beta, theta, mu, X):
    """
    L_stat: mean over batch of the variance of OU residuals within each window.
    epsilon_s = Delta_Z_s - theta*(mu - Z_{s-1})   (Eq. 41-42)
    Uses locally-normalised log-prices as a proxy for the spread.
    """
    lp1 = X[:, :, 0]   # (B, W) normalised log s1
    lp2 = X[:, :, 1]   # (B, W) normalised log s2
    Z     = lp1 - beta.unsqueeze(1) * lp2          # (B, W)
    dZ    = Z[:, 1:] - Z[:, :-1]                   # (B, W-1)
    Z_lag = Z[:, :-1]                               # (B, W-1)
    drift = theta.unsqueeze(1) * (mu.unsqueeze(1) - Z_lag)
    eps   = dZ - drift
    return eps.var(dim=1).mean()


def smoothness_loss(beta_curr, beta_prev):
    """L_smooth: penalise rapid changes in hedge ratio (Eq. 43)."""
    return ((beta_curr - beta_prev) ** 2).mean()


print("Loss functions defined.")

model     = PairsLSTM(hidden_dim=64, num_layers=2, dropout=0.2).to(DEVICE)
optimiser = AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
scheduler = CosineAnnealingLR(optimiser, T_max=EPOCHS, eta_min=1e-5)

train_losses, val_losses = [], []
best_val, best_state = float("inf"), None

for epoch in range(1, EPOCHS + 1):
    # ── Train ──────────────────────────────────────────────────────────────
    model.train()
    epoch_loss = 0.0
    prev_beta  = None
    for (Xb,) in train_dl:
        Xb = Xb.to(DEVICE)
        beta, theta, mu = model(Xb)
        l_stat   = stationarity_loss(beta, theta, mu, Xb)
        l_smooth = (smoothness_loss(beta, prev_beta.to(DEVICE))
                    if prev_beta is not None
                    else torch.tensor(0.0, device=DEVICE))
        loss = l_stat + LAMBDA_SMOOTH * l_smooth
        optimiser.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimiser.step()
        epoch_loss += loss.item()
        prev_beta   = beta.detach().cpu()

    avg_train = epoch_loss / len(train_dl)

    # ── Validate ────────────────────────────────────────────────────────────
    model.eval()
    vl, prev_bv = 0.0, None
    with torch.no_grad():
        for (Xb,) in val_dl:
            Xb = Xb.to(DEVICE)
            beta, theta, mu = model(Xb)
            ls  = stationarity_loss(beta, theta, mu, Xb)
            lsm = (smoothness_loss(beta, prev_bv.to(DEVICE))
                   if prev_bv is not None
                   else torch.tensor(0.0, device=DEVICE))
            vl += (ls + LAMBDA_SMOOTH * lsm).item()
            prev_bv = beta.detach().cpu()
    avg_val = vl / max(len(val_dl), 1)

    train_losses.append(avg_train)
    val_losses.append(avg_val)
    scheduler.step()

    if avg_val < best_val:
        best_val   = avg_val
        best_state = {k: v.clone() for k, v in model.state_dict().items()}

    if epoch % 10 == 0:
        print(f"Epoch {epoch:3d}/{EPOCHS}  train={avg_train:.6f}  val={avg_val:.6f}")

model.load_state_dict(best_state)
print(f"\nDone. Best val loss: {best_val:.6f}")

fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(train_losses, color=COLORS[0], label="Train")
ax.plot(val_losses,   color=COLORS[1], label="Validation")
ax.set_xlabel("Epoch")
ax.set_ylabel("L_stat + lambda * L_smooth")
ax.set_title("LSTM Training Curves", fontweight="bold")
ax.legend()
plt.tight_layout()
plt.show()

# Prepend enough train tail to provide initial window context
full_prices = pd.concat([train_prices.iloc[-WINDOW:], test_prices])
X_full      = make_windows(full_prices, S1_NAME, S2_NAME, WINDOW)
inf_dates   = full_prices.index[WINDOW - 1:]

model.eval()
betas_dyn, thetas_dyn, mus_dyn = [], [], []
with torch.no_grad():
    for i in range(len(X_full)):
        x = X_full[i:i+1].to(DEVICE)
        b, t, m = model(x)
        betas_dyn.append(b.item())
        thetas_dyn.append(t.item())
        mus_dyn.append(m.item())

betas_dyn  = np.array(betas_dyn,  dtype=np.float32)
thetas_dyn = np.array(thetas_dyn, dtype=np.float32)
mus_dyn    = np.array(mus_dyn,    dtype=np.float32)

inf_p1 = full_prices[S1_NAME].values[WINDOW - 1:].astype(np.float32)
inf_p2 = full_prices[S2_NAME].values[WINDOW - 1:].astype(np.float32)

# Dynamic spread Z^dyn_t = S1(t) - beta_hat_t * S2(t)  (Eq. 40)
Z_dyn = inf_p1 - betas_dyn * inf_p2

# Estimate sigma_eps via rolling OU residual std
sigma_eps = np.full(len(Z_dyn), OU_SIGMA, dtype=np.float32)
for i in range(WINDOW, len(Z_dyn)):
    dz    = np.diff(Z_dyn[i - WINDOW:i])
    drift = thetas_dyn[i] * (mus_dyn[i] - Z_dyn[i - WINDOW:i - 1])
    sigma_eps[i] = float(np.std(dz - drift) + 1e-8)

# OU stationary std  sigma_inf = sqrt(sigma_eps^2 / 2*theta)  (Eq. 45 / Theorem 1.2)
sigma_inf_dyn = np.sqrt(sigma_eps ** 2 / (2.0 * thetas_dyn + 1e-8))

# Dynamic z-score  (Eq. 45)
zscore_dyn = (Z_dyn - mus_dyn) / (sigma_inf_dyn + 1e-8)

# Static baseline spread + rolling z-score (Eq. 46)
Z_static   = inf_p1 - BETA_STATIC * inf_p2
ROLL       = max(int(HALF_LIFE * 2), 5)
mu_roll    = pd.Series(Z_static).rolling(ROLL).mean().fillna(OU_MU).values
std_roll   = pd.Series(Z_static).rolling(ROLL).std().fillna(OU_SIGMA).values
zscore_stat = (Z_static - mu_roll) / (std_roll + 1e-8)

inf_df = pd.DataFrame({
    "p1": inf_p1, "p2": inf_p2,
    "beta_dyn":    betas_dyn,
    "theta_dyn":   thetas_dyn,
    "mu_dyn":      mus_dyn,
    "Z_dyn":       Z_dyn,
    "zscore_dyn":  zscore_dyn,
    "Z_static":    Z_static,
    "zscore_stat": zscore_stat,
}, index=inf_dates)

test_inf = inf_df.loc[test_prices.index].copy()
print(f"Test inference rows: {len(test_inf)}")
test_inf.head(3)

Z_ENTRY = 1.5
Z_EXIT  = 0.3
Z_STOP  = 3.0


def generate_signals(zscore):
    """
    Stateful signal generator — Eq. 47.
    +1 = long spread, -1 = short spread, 0 = flat.
    Stop-loss applied at |z| > Z_STOP.
    """
    signal   = np.zeros(len(zscore), dtype=np.float32)
    position = 0.0
    for t in range(len(zscore)):
        z = float(zscore[t])
        if not np.isfinite(z):
            position = 0.0
        else:
            if abs(z) > Z_STOP:
                position = 0.0
            if position != 0 and abs(z) < Z_EXIT:
                position = 0.0
            if position == 0:
                if z < -Z_ENTRY:
                    position = 1.0
                elif z > Z_ENTRY:
                    position = -1.0
        signal[t] = position
    return signal


test_inf["signal_dyn"]  = generate_signals(test_inf["zscore_dyn"].values)
test_inf["signal_stat"] = generate_signals(test_inf["zscore_stat"].values)

print("Signal distribution — Dynamic:")
print(test_inf["signal_dyn"].value_counts().to_string())
print("\nSignal distribution — Static:")
print(test_inf["signal_stat"].value_counts().to_string())

def spread_returns(Z):
    """r^Z_t = (Z_t - Z_{t-1}) / |Z_{t-1}|  (Eq. 48)."""
    denom      = np.abs(np.roll(Z, 1))
    denom[0]   = np.nan
    denom      = np.where(denom < 1e-8, 1e-8, denom)
    return np.concatenate([[np.nan], np.diff(Z)]) / denom


def backtest(Z, signal, cost=TRANSACTION_COST, label=""):
    """
    Full backtest with 1-period signal lag (Eq. 58) and transaction costs (Eq. 50).
    Returns daily P&L series + performance metrics.
    """
    r_z      = spread_returns(Z)
    sig      = np.roll(signal, 1);  sig[0] = 0.0    # lookahead guard (Eq. 58)
    r_strat  = sig * r_z                             # Eq. 49
    turnover = np.abs(np.diff(signal, prepend=0.0))
    r_net    = r_strat - cost * turnover             # Eq. 50
    r_net    = np.where(np.isfinite(r_net), r_net, 0.0)

    wealth   = np.cumprod(1 + r_net)                 # Eq. 51

    mu_r  = np.mean(r_net)
    std_r = np.std(r_net) + 1e-10
    SR    = mu_r / std_r * np.sqrt(252)              # Eq. 52

    peak    = np.maximum.accumulate(wealth)
    dd      = (peak - wealth) / (peak + 1e-10)
    MDD     = dd.max()                               # Eq. 53

    ann_ret = wealth[-1] ** (252.0 / len(wealth)) - 1
    calmar  = ann_ret / (MDD + 1e-10)                # Eq. 54

    wins      = r_net > 0
    win_rate  = wins.mean()                          # Eq. 56
    pf        = r_net[wins].sum() / (abs(r_net[~wins].sum()) + 1e-10)  # Eq. 57
    n_trades  = int((turnover > 0).sum())

    return {
        "label":    label,
        "r_net":    r_net,
        "wealth":   wealth,
        "SR":       SR,
        "ann_ret":  ann_ret,
        "MDD":      MDD,
        "calmar":   calmar,
        "win_rate": win_rate,
        "pf":       pf,
        "n_trades": n_trades,
    }


bt_dyn  = backtest(test_inf["Z_dyn"].values,   test_inf["signal_dyn"].values,  label="LSTM Dynamic")
bt_stat = backtest(test_inf["Z_static"].values, test_inf["signal_stat"].values, label="Static Johansen")

print("{:<25} {:>11} {:>10} {:>9} {:>9} {:>9} {:>10} {:>9}".format(
    "Strategy", "Ann.Ret", "Sharpe", "MDD", "Calmar", "Win%", "ProfFact", "#Trades"))
print("-" * 95)
for bt in [bt_dyn, bt_stat]:
    print("{:<25} {:>10.2%} {:>10.3f} {:>8.2%} {:>9.2f} {:>8.2%} {:>10.2f} {:>9d}".format(
        bt["label"], bt["ann_ret"], bt["SR"], bt["MDD"],
        bt["calmar"], bt["win_rate"], bt["pf"], bt["n_trades"]))

dates = test_inf.index

fig = plt.figure(figsize=(16, 18))
gs  = gridspec.GridSpec(4, 2, figure=fig, hspace=0.45, wspace=0.35)

# 1 — Cumulative wealth
ax1 = fig.add_subplot(gs[0, :])
ax1.plot(dates, bt_dyn["wealth"],  color=COLORS[0], lw=1.8, label="LSTM Dynamic")
ax1.plot(dates, bt_stat["wealth"], color=COLORS[1], lw=1.8, ls="--", label="Static Johansen")
ax1.set_title("Cumulative Wealth — Out-of-Sample", fontweight="bold")
ax1.set_ylabel("Portfolio value (start=1)")
ax1.legend()

# 2 — Dynamic vs static beta
ax2 = fig.add_subplot(gs[1, 0])
ax2.plot(dates, test_inf["beta_dyn"], color=COLORS[2], lw=0.9, label="beta_t (LSTM)")
ax2.axhline(BETA_STATIC, color=COLORS[1], ls="--", lw=1.2, label=f"beta* static={BETA_STATIC:.3f}")
ax2.set_title("Dynamic vs Static Hedge Ratio", fontweight="bold")
ax2.set_ylabel("beta")
ax2.legend()

# 3 — Adaptive half-life
ax3 = fig.add_subplot(gs[1, 1])
hl_dyn = np.log(2) / (test_inf["theta_dyn"].values + 1e-8)
ax3.plot(dates, hl_dyn, color=COLORS[3], lw=0.9)
ax3.axhline(HALF_LIFE, color="grey", ls="--", lw=1.0, label=f"static HL={HALF_LIFE:.1f}d")
ax3.set_ylim(0, 60)
ax3.set_title("Adaptive Half-Life (days)", fontweight="bold")
ax3.set_ylabel("Half-life (days)")
ax3.legend()

# 4 — Z-score with shaded positions
ax4 = fig.add_subplot(gs[2, :])
ax4.plot(dates, test_inf["zscore_dyn"], color=COLORS[0], lw=0.7, label="z-score (dynamic)")
for thr, col, ls in [(Z_ENTRY, "red", "--"), (-Z_ENTRY, "green", "--"),
                     (Z_STOP,  "black", ":"), (-Z_STOP, "black", ":"),
                     (Z_EXIT,  "grey", "-."), (-Z_EXIT,  "grey", "-.")]:
    ax4.axhline(thr, color=col, ls=ls, lw=0.8)
sig_arr = test_inf["signal_dyn"].values
for t_idx in range(1, len(dates)):
    s = sig_arr[t_idx]
    if s == 1:
        ax4.axvspan(dates[t_idx - 1], dates[t_idx], alpha=0.08, color="green")
    elif s == -1:
        ax4.axvspan(dates[t_idx - 1], dates[t_idx], alpha=0.08, color="red")
ax4.set_title("Dynamic Z-Score with Entry / Exit Signals", fontweight="bold")
ax4.set_ylabel("Z-score")
ax4.legend()

# 5 — Drawdown
def dd_series(w):
    pk = np.maximum.accumulate(w)
    return (w - pk) / (pk + 1e-10)

ax5 = fig.add_subplot(gs[3, 0])
ax5.fill_between(dates, dd_series(bt_dyn["wealth"]),  alpha=0.5, color=COLORS[0], label="LSTM Dynamic")
ax5.fill_between(dates, dd_series(bt_stat["wealth"]), alpha=0.5, color=COLORS[1], label="Static")
ax5.set_title("Drawdown", fontweight="bold")
ax5.set_ylabel("Drawdown")
ax5.legend()

# 6 — Metrics comparison
ax6 = fig.add_subplot(gs[3, 1])
m_names = ["Sharpe", "Calmar", "ProfFact", "WinRate x10"]
m_dyn   = [bt_dyn["SR"],  bt_dyn["calmar"],  bt_dyn["pf"],  bt_dyn["win_rate"]  * 10]
m_stat  = [bt_stat["SR"], bt_stat["calmar"], bt_stat["pf"], bt_stat["win_rate"] * 10]
x = np.arange(len(m_names))
w = 0.35
ax6.bar(x - w/2, m_dyn,  w, color=COLORS[0], label="LSTM Dynamic")
ax6.bar(x + w/2, m_stat, w, color=COLORS[1], label="Static Johansen")
ax6.set_xticks(x)
ax6.set_xticklabels(m_names)
ax6.set_title("Performance Metrics", fontweight="bold")
ax6.legend()

plt.suptitle(
    f"Pairs Trading: {S1_NAME} / {S2_NAME}   "
    f"OOS: {test_prices.index[0].date()} -> {test_prices.index[-1].date()}",
    fontsize=13, fontweight="bold", y=1.01,
)
plt.savefig("backtest_dashboard.png", dpi=130, bbox_inches="tight")
plt.show()

N_FOLDS    = 3
WFV_EPOCHS = 40   # fewer epochs per fold for speed

fold_size   = len(prices) // (N_FOLDS + 1)
wfv_results = []

print(f"Walk-forward: {N_FOLDS} folds, ~{fold_size} days per fold")

for k in range(N_FOLDS):
    train_end  = fold_size * (k + 1)
    test_end   = fold_size * (k + 2)
    fold_train = prices.iloc[:train_end]
    fold_test  = prices.iloc[train_end:test_end]
    if len(fold_test) < WINDOW + 20:
        continue

    # Re-estimate static OU params for this fold
    joh_k     = johansen_hedge_ratio(fold_train[S1_NAME], fold_train[S2_NAME])
    beta_k    = joh_k["beta"]
    spread_k  = fold_train[S1_NAME] - beta_k * fold_train[S2_NAME]
    ou_k      = fit_ou_params(spread_k)

    # Build windows and re-train LSTM from scratch
    Xk   = make_windows(fold_train, S1_NAME, S2_NAME, WINDOW)
    dl_k = DataLoader(TensorDataset(Xk), batch_size=BATCH_SIZE, shuffle=True, drop_last=True)

    model_k = PairsLSTM(hidden_dim=64, num_layers=2).to(DEVICE)
    opt_k   = AdamW(model_k.parameters(), lr=LR)

    model_k.train()
    prev_bk = None
    for _ in range(WFV_EPOCHS):
        for (Xb,) in dl_k:
            Xb = Xb.to(DEVICE)
            b, t, m = model_k(Xb)
            ls  = stationarity_loss(b, t, m, Xb)
            lsm = (smoothness_loss(b, prev_bk.to(DEVICE))
                   if prev_bk is not None
                   else torch.tensor(0.0, device=DEVICE))
            loss_k = ls + LAMBDA_SMOOTH * lsm
            opt_k.zero_grad()
            loss_k.backward()
            nn.utils.clip_grad_norm_(model_k.parameters(), 1.0)
            opt_k.step()
            prev_bk = b.detach().cpu()

    # Inference on test fold
    full_k  = pd.concat([fold_train.iloc[-WINDOW:], fold_test])
    Xk_inf  = make_windows(full_k, S1_NAME, S2_NAME, WINDOW)
    model_k.eval()
    bk, tk, mk = [], [], []
    with torch.no_grad():
        for i in range(len(Xk_inf)):
            xi = Xk_inf[i:i+1].to(DEVICE)
            b_, t_, m_ = model_k(xi)
            bk.append(b_.item())
            tk.append(t_.item())
            mk.append(m_.item())

    bk = np.array(bk, dtype=np.float32)
    tk = np.array(tk, dtype=np.float32)
    mk = np.array(mk, dtype=np.float32)

    n_test_k = len(fold_test)
    p1k = full_k[S1_NAME].values[WINDOW - 1:].astype(np.float32)
    p2k = full_k[S2_NAME].values[WINDOW - 1:].astype(np.float32)
    Zk_all  = p1k - bk * p2k
    sig_inf_k = np.sqrt(ou_k["sigma"] ** 2 / (2.0 * tk + 1e-8))
    zs_k    = (Zk_all - mk) / (sig_inf_k + 1e-8)

    # Keep test portion only
    Zk_test = Zk_all[-n_test_k:]
    zs_test = zs_k[-n_test_k:]
    sig_k   = generate_signals(zs_test)
    bt_k    = backtest(Zk_test, sig_k, label=f"Fold {k+1}")

    wfv_results.append({
        "fold": k + 1,
        "train_days": train_end,
        "test_days":  n_test_k,
        "SR_oos":     bt_k["SR"],
        "ann_ret":    bt_k["ann_ret"],
        "MDD":        bt_k["MDD"],
    })
    print(f"  Fold {k+1}: OOS Sharpe={bt_k['SR']:.3f}  "
          f"Ann.Ret={bt_k['ann_ret']:.2%}  MDD={bt_k['MDD']:.2%}")

wfv_df = pd.DataFrame(wfv_results)
print(f"\nMean OOS Sharpe: {wfv_df['SR_oos'].mean():.3f}")
wfv_df

summary = pd.DataFrame([
    {
        "Strategy":      bt["label"],
        "OOS Sharpe":    round(bt["SR"], 3),
        "Ann. Return":   f"{bt['ann_ret']:.2%}",
        "Max Drawdown":  f"{bt['MDD']:.2%}",
        "Calmar":        round(bt["calmar"], 2),
        "Win Rate":      f"{bt['win_rate']:.2%}",
        "Profit Factor": round(bt["pf"], 2),
        "Trades":        bt["n_trades"],
    }
    for bt in [bt_dyn, bt_stat]
])

print("=" * 90)
print(f"  BACKTEST SUMMARY   {S1_NAME} / {S2_NAME}")
print(f"  OOS period: {test_prices.index[0].date()} -> {test_prices.index[-1].date()}")
print("=" * 90)
print(summary.to_string(index=False))

print("\nSharpe interpretation:")
for bt in [bt_dyn, bt_stat]:
    sr = bt["SR"]
    grade = ("Exceptional" if sr > 2.0 else
             "Good"        if sr > 1.0 else
             "Acceptable"  if sr > 0.5 else "Poor")
    print(f"  {bt['label']:<25}: SR={sr:.3f}  -> {grade}")

if not wfv_df.empty:
    sr_oos = wfv_df["SR_oos"].mean()
    verdict = "ROBUST" if sr_oos > 0.5 else "MARGINAL"
    print(f"\nWalk-forward mean OOS Sharpe = {sr_oos:.3f}  -> {verdict} (threshold 0.5, Eq. 59)")

